
#define SOFTDEVICE_ENABLED 1

#define APPLICATION_IRQ_HIGHEST_PRIORITY 2
#define APPLICATION_IRQ_HIGH_PRIORITY	 3
#define APPLICATION_IRQ_LOW_PRIORITY	 6
#define APPLICATION_IRQ_LOWEST_PRIORITY	 7

#define UART_PRIORITY					 APPLICATION_IRQ_HIGHEST_PRIORITY

#define SPI0_PRIORITY					 APPLICATION_IRQ_LOW_PRIORITY
#define SPI1_PRIORITY					 APPLICATION_IRQ_LOW_PRIORITY

#define RTC0_PRIORITY					 APPLICATION_IRQ_LOWEST_PRIORITY
#define RTC1_PRIORITY					 APPLICATION_IRQ_HIGH_PRIORITY
#define RTC2_PRIORITY					 APPLICATION_IRQ_HIGH_PRIORITY
